[2025-06-09T07:07:18.140+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T07:07:18.178+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netsuite_saved_search_4532.download_saved_search manual__2025-06-09T07:07:14.134904+00:00 [queued]>
[2025-06-09T07:07:18.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netsuite_saved_search_4532.download_saved_search manual__2025-06-09T07:07:14.134904+00:00 [queued]>
[2025-06-09T07:07:18.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-09T07:07:18.208+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_saved_search> on 2025-06-09 07:07:14.134904+00:00
[2025-06-09T07:07:18.213+0000] {standard_task_runner.py:63} INFO - Started process 34 to run task
[2025-06-09T07:07:18.219+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'netsuite_saved_search_4532', 'download_saved_search', 'manual__2025-06-09T07:07:14.134904+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/netsuite_4532_dag.py', '--cfg-path', '/tmp/tmpj8ak2ntr']
[2025-06-09T07:07:18.221+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask download_saved_search
[2025-06-09T07:07:18.271+0000] {task_command.py:426} INFO - Running <TaskInstance: netsuite_saved_search_4532.download_saved_search manual__2025-06-09T07:07:14.134904+00:00 [running]> on host 1e2e6e9ca95e
[2025-06-09T07:07:18.425+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='netsuite_saved_search_4532' AIRFLOW_CTX_TASK_ID='download_saved_search' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T07:07:14.134904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T07:07:14.134904+00:00'
[2025-06-09T07:07:18.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T07:08:00.519+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T07:08:00.527+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/netsuite_4532_dag.py", line 62, in download_saved_search_4532
    with open(file_path, 'w', encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/netsuite/CustomSavedSearch_4532.csv'
[2025-06-09T07:08:00.564+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=netsuite_saved_search_4532, task_id=download_saved_search, run_id=manual__2025-06-09T07:07:14.134904+00:00, execution_date=20250609T070714, start_date=20250609T070718, end_date=20250609T070800
[2025-06-09T07:08:00.626+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 357 for task download_saved_search ([Errno 13] Permission denied: '/opt/airflow/data/netsuite/CustomSavedSearch_4532.csv'; 34)
[2025-06-09T07:08:00.690+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T07:08:00.721+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T07:08:00.725+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
