[2025-06-04T09:20:23.763+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-04T09:20:23.788+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_create_table_and_read_dag.read_postgres_data manual__2025-06-04T09:20:20.612999+00:00 [queued]>
[2025-06-04T09:20:23.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_create_table_and_read_dag.read_postgres_data manual__2025-06-04T09:20:20.612999+00:00 [queued]>
[2025-06-04T09:20:23.797+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-04T09:20:23.810+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_postgres_data> on 2025-06-04 09:20:20.612999+00:00
[2025-06-04T09:20:23.814+0000] {standard_task_runner.py:63} INFO - Started process 36 to run task
[2025-06-04T09:20:23.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_create_table_and_read_dag', 'read_postgres_data', 'manual__2025-06-04T09:20:20.612999+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/test_postgres_conn_and_create_table.py', '--cfg-path', '/tmp/tmp_peuj2tc']
[2025-06-04T09:20:23.818+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask read_postgres_data
[2025-06-04T09:20:23.866+0000] {task_command.py:426} INFO - Running <TaskInstance: test_postgres_create_table_and_read_dag.read_postgres_data manual__2025-06-04T09:20:20.612999+00:00 [running]> on host 8b60c3c987d2
[2025-06-04T09:20:23.959+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_create_table_and_read_dag' AIRFLOW_CTX_TASK_ID='read_postgres_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T09:20:20.612999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T09:20:20.612999+00:00'
[2025-06-04T09:20:23.960+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-04T09:20:23.981+0000] {base.py:84} INFO - Using connection ID 'datalake_***' for task execution.
[2025-06-04T09:20:24.031+0000] {logging_mixin.py:188} INFO - ✅ Đọc được 0 dòng dữ liệu:
[2025-06-04T09:20:24.031+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-04T09:20:24.032+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-04T09:20:24.040+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_postgres_create_table_and_read_dag, task_id=read_postgres_data, run_id=manual__2025-06-04T09:20:20.612999+00:00, execution_date=20250604T092020, start_date=20250604T092023, end_date=20250604T092024
[2025-06-04T09:20:24.070+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-04T09:20:24.122+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-04T09:20:24.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
