[2025-06-09T06:40:07.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T06:40:08.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-03-03T00:00:00+00:00 [queued]>
[2025-06-09T06:40:08.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-03-03T00:00:00+00:00 [queued]>
[2025-06-09T06:40:08.162+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T06:40:09.329+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_netsuite> on 2024-03-03 00:00:00+00:00
[2025-06-09T06:40:09.594+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2025-06-09T06:40:10.960+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'netsuite_4532_to_dwh', 'extract_from_netsuite', 'scheduled__2024-03-03T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/netsuite_4532_dag.py', '--cfg-path', '/tmp/tmpod_hyyje']
[2025-06-09T06:40:11.196+0000] {standard_task_runner.py:91} INFO - Job 266: Subtask extract_from_netsuite
[2025-06-09T06:40:12.828+0000] {task_command.py:426} INFO - Running <TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-03-03T00:00:00+00:00 [running]> on host 6b5241449da9
[2025-06-09T06:40:16.688+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='netsuite_4532_to_dwh' AIRFLOW_CTX_TASK_ID='extract_from_netsuite' AIRFLOW_CTX_EXECUTION_DATE='2024-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-03T00:00:00+00:00'
[2025-06-09T06:40:16.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T06:40:21.694+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T06:40:21.806+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/netsuite_4532_dag.py", line 43, in extract_from_netsuite
    raise Exception("❌ Đăng nhập NetSuite thất bại hoặc trả về HTML")
Exception: ❌ Đăng nhập NetSuite thất bại hoặc trả về HTML
[2025-06-09T06:40:24.278+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=netsuite_4532_to_dwh, task_id=extract_from_netsuite, run_id=scheduled__2024-03-03T00:00:00+00:00, execution_date=20240303T000000, start_date=20250609T064008, end_date=20250609T064024
[2025-06-09T06:40:24.590+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 266 for task extract_from_netsuite (❌ Đăng nhập NetSuite thất bại hoặc trả về HTML; 237)
[2025-06-09T06:40:25.019+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T06:40:25.093+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
