[2025-06-09T06:39:43.344+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T06:39:43.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2025-06-09T06:39:43.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2025-06-09T06:39:43.674+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-09T06:39:43.920+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_netsuite> on 2024-02-26 00:00:00+00:00
[2025-06-09T06:39:44.231+0000] {standard_task_runner.py:63} INFO - Started process 223 to run task
[2025-06-09T06:39:44.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'netsuite_4532_to_dwh', 'extract_from_netsuite', 'scheduled__2024-02-26T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/netsuite_4532_dag.py', '--cfg-path', '/tmp/tmpcec1sr6w']
[2025-06-09T06:39:44.261+0000] {standard_task_runner.py:91} INFO - Job 258: Subtask extract_from_netsuite
[2025-06-09T06:39:44.921+0000] {task_command.py:426} INFO - Running <TaskInstance: netsuite_4532_to_dwh.extract_from_netsuite scheduled__2024-02-26T00:00:00+00:00 [running]> on host 6b5241449da9
[2025-06-09T06:39:45.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='netsuite_4532_to_dwh' AIRFLOW_CTX_TASK_ID='extract_from_netsuite' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T00:00:00+00:00'
[2025-06-09T06:39:45.331+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T06:39:48.527+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T06:39:48.536+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/netsuite_4532_dag.py", line 43, in extract_from_netsuite
    raise Exception("❌ Đăng nhập NetSuite thất bại hoặc trả về HTML")
Exception: ❌ Đăng nhập NetSuite thất bại hoặc trả về HTML
[2025-06-09T06:39:50.482+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=netsuite_4532_to_dwh, task_id=extract_from_netsuite, run_id=scheduled__2024-02-26T00:00:00+00:00, execution_date=20240226T000000, start_date=20250609T063943, end_date=20250609T063950
[2025-06-09T06:39:51.075+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 258 for task extract_from_netsuite (❌ Đăng nhập NetSuite thất bại hoặc trả về HTML; 223)
[2025-06-09T06:39:51.719+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T06:39:52.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
