[2025-06-09T04:08:47.021+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-09T04:08:47.050+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T03:58:09.686965+00:00 [queued]>
[2025-06-09T04:08:47.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T03:58:09.686965+00:00 [queued]>
[2025-06-09T04:08:47.065+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-06-09T04:08:47.085+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_netsuite_invoice> on 2025-06-09 03:58:09.686965+00:00
[2025-06-09T04:08:47.093+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2025-06-09T04:08:47.097+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NetSuite_Invoice_Daily_Extractor', 'fetch_netsuite_invoice', 'manual__2025-06-09T03:58:09.686965+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/crawl_netsuite.py', '--cfg-path', '/tmp/tmp3gut4u6l']
[2025-06-09T04:08:47.100+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask fetch_netsuite_invoice
[2025-06-09T04:08:47.166+0000] {task_command.py:426} INFO - Running <TaskInstance: NetSuite_Invoice_Daily_Extractor.fetch_netsuite_invoice manual__2025-06-09T03:58:09.686965+00:00 [running]> on host 6b5241449da9
[2025-06-09T04:08:47.244+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='NetSuite_Invoice_Daily_Extractor' AIRFLOW_CTX_TASK_ID='fetch_netsuite_invoice' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T03:58:09.686965+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T03:58:09.686965+00:00'
[2025-06-09T04:08:47.245+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-09T04:08:48.146+0000] {logging_mixin.py:188} INFO - ‚úÖ ƒêƒÉng nh·∫≠p th√†nh c√¥ng.
[2025-06-09T04:08:48.572+0000] {logging_mixin.py:188} INFO - üìÑ N·ªôi dung response ƒë∆∞·ª£c ghi v√†o: /tmp/debug_invoice_raw.txt
[2025-06-09T04:08:48.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-09T04:08:48.573+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawl_netsuite.py", line 51, in fetch_invoice_data
    raise Exception("‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.")
Exception: ‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.
[2025-06-09T04:08:48.587+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=NetSuite_Invoice_Daily_Extractor, task_id=fetch_netsuite_invoice, run_id=manual__2025-06-09T03:58:09.686965+00:00, execution_date=20250609T035809, start_date=20250609T040847, end_date=20250609T040848
[2025-06-09T04:08:48.602+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task fetch_netsuite_invoice (‚ùå NetSuite tr·∫£ v·ªÅ HTML thay v√¨ CSV. C√≥ th·ªÉ l·ªói quy·ªÅn, session timeout, ho·∫∑c c·∫ßn re-auth.; 63)
[2025-06-09T04:08:48.641+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-09T04:08:48.680+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-09T04:08:48.685+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
